### PR TITLE
Include src files in published package

### LINKED ISSUE #26: Strange Warning in Angular: "Cannot find source file"
```
WARNING in ./node_modules/json-to-graphql-query/lib/types/EnumType.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/types/EnumType.ts': Error: Can't resolve '../../src/types/EnumType.ts' in '/Projects/activeql.d/activeql/angular/node_modules/json-to-graphql-query/lib/types'
```

Everything seems to work, I still like to figure out what's causes the warning, though. Any idea?

### PR DESCRIPTION
**Pull request by esetnik**
Resolves #26

### CODE REVIEW

**Review by cclews1 — APPROVED** [review]
Removes source map warning from webpack build phase due to failed Source Map parsing.

Please approve.

**Comment by esetnik** [comment]
@vkolagi any chance you can get this reviewed and merged please?

**Review by plmercereau — APPROVED** [review]

**Comment by esetnik** [comment]
@plmercereau thanks. Will you also publish a new version to npm?

**Comment by plmercereau** [comment]
I can only approve the PR (as a former contributor I guess), but I cannot merge the PR and publish a new version. Hopefully @vkolgi will be able to do it soon :)

**Comment by esetnik** [comment]
> I can only approve the PR (as a former contributor I guess), but I cannot merge the PR and publish a new version. Hopefully @vkolgi will be able to do it soon :)

If we don't hear back from @vkolagi soon I will simply fork the repo and publish a new version on npm under my own account.

**Comment by plmercereau** [comment]
> > I can only approve the PR (as a former contributor I guess), but I cannot merge the PR and publish a new version. Hopefully @vkolgi will be able to do it soon :)
> 
> If we don't hear back from @vkolagi soon I will simply fork the repo and publish a new version on npm under my own account.

Yes, that would probably solve your problem... I hope however we would hear from @vkolgi. Maybe if they don't have enough bandwidth to maintain this repo, we could join forces to maintain it with a few more motivated contributors? This library is too nice to be abandoned!! What do you think, @vkolgi ?

**Comment by esetnik** [comment]
It looks like @vkolgi took over the project from @dupski but @vkolagi has no git activity at all in the last several years so i'm not hopeful this will happen.

**Comment by dupski** [comment]
Sorry to hear this guys. Hopefully @vkolagi will have a look at this very shortly, if not I think I still have rights on the NPM repository so if one of you guys would like to take the mantle moving forward I can give you access to publish to NPM (after a little vetting of course).

**Comment by vkolgi** [comment]
@dupski I just saw this. I will approve and release the new version in NPM.
We can also extend the approving rights to former contributors who worked on this.

**Review by vkolgi — APPROVED** [review]
Looks good

**Comment by dupski** [comment]
Brill, thanks for jumping back on it @vkolgi , it's great to see the library is still being used 🙂👍

**Pull request merged**
