### PR TITLE
Fixing empty variables, empty directives

### PR DESCRIPTION
**Pull request by MorganDbs**
Hey @vkolgi it's us again :),

We just noticed an usecase where someone would put empty variable object or empty directive object and breaking the gql query.
So here a quick fix. 

Hope you can merge and publish new version soon :dancers: 

Best regards

### CODE REVIEW

**Comment by MorganDbs** [comment]
@vkolgi  Any news? :)

**Comment by MorganDbs** [comment]
@vkolgi @vkolagi 
Hello, sorry to bother you again but can you merge and publish my fix asap please ? :smile: 

Best regards

**Comment by MorganDbs** [comment]
@vkolgi @vkolagi 
Hey, thanks for the merge ! When do you plan to publish new version ?

**Comment by vkolgi** [comment]
@MorganDbs hey, I am planning to publish new version today.

**Pull request merged**
