### PR TITLE
support name

### PR DESCRIPTION
**Pull request by peng-huang-cc**

### CODE REVIEW

**Comment by diegovdc** [comment]
Any chance on getting this PR merged?

**Comment by dupski** [comment]
Hi @diegovdc , apologies, I am not working with GraphQL in my day job any more which is why I'm not updating this repo that often.

If you or anyone you know would be interested in maintaining this library moving forward I'd be happy to transfer it.

I've put in a reminder for the weekend to take a look, hopefully will have time then.

**Comment by diegovdc** [comment]
Sorry, I can't become a maintainer at the moment, but if the feature is working, would it be too problematic to merge?

**Comment by dupski** [comment]
No not at all, I just need to find time to do it, and remember the process. Will get to it when I can :)

**Comment by aylabbs** [comment]
Hi, @vkolgi, generous new maintainer!

Can this be merged when you have a moment?

**Comment by vkolgi** [comment]
@peng-huang-cc thanks for the contribution, really appreciate it. 
I moved contents of the file example.tests to name.tests file.
Otherwise changes look good.

**Review by vkolgi — APPROVED** [review]
Looks good.

**Pull request merged**
